#!/usr/bin/env bun
/**
 * Copies the hosted migration-support registry snapshot into the public
 * scanner so `flagshark scan` classifies lock-in from exactly the cells the
 * hosted product admits — never from a hand-maintained list that could drift.
 *
 * Usage:
 *   bun scripts/sync-support-snapshot.ts <path/to/adoption-support-snapshot.json>
 *
 * Writes two files under packages/core/src/migration/:
 *   - support-snapshot.json      verbatim (re-serialised) copy, for review and diffing
 *   - support-snapshot.data.ts   the same object as a TypeScript module
 *
 * The `.data.ts` module exists because `@flagshark/core` ships tsc output that
 * Node loads directly (the CLI marks core as external). A runtime JSON import
 * there would need import attributes (Node >= 18.20 / 20.10), and the repo
 * already inlines tree-sitter queries for the same reason. A test pins the two
 * files to each other.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const outDir = resolve(here, '..', 'packages', 'core', 'src', 'migration')
const jsonOut = resolve(outDir, 'support-snapshot.json')
const tsOut = resolve(outDir, 'support-snapshot.data.ts')

const sourcePath = process.argv[2]
if (!sourcePath) {
  console.error('usage: bun scripts/sync-support-snapshot.ts <adoption-support-snapshot.json>')
  process.exit(2)
}

const raw = JSON.parse(readFileSync(resolve(sourcePath), 'utf8')) as Record<string, unknown>

if (raw.schemaVersion !== 1) {
  console.error(`refusing to sync: schemaVersion must be 1, got ${JSON.stringify(raw.schemaVersion)}`)
  process.exit(1)
}
if (typeof raw.sourceRevision !== 'string' || raw.sourceRevision.length === 0) {
  console.error('refusing to sync: sourceRevision is missing')
  process.exit(1)
}
if (!Array.isArray(raw.cells) || raw.cells.length === 0) {
  console.error('refusing to sync: cells must be a non-empty array')
  process.exit(1)
}

const json = JSON.stringify(raw, null, 2) + '\n'
writeFileSync(jsonOut, json)

const ts =
  '// GENERATED by scripts/sync-support-snapshot.ts — do not edit by hand.\n' +
  '// Source: the private FlagShark capability registry (see README.md in this directory).\n' +
  `// sourceRevision: ${raw.sourceRevision}\n` +
  '\n' +
  'export const SUPPORT_SNAPSHOT_DATA = ' +
  JSON.stringify(raw, null, 2) +
  ' as const\n'
writeFileSync(tsOut, ts)

console.log(
  `synced ${raw.cells.length} cells (sourceRevision ${raw.sourceRevision}, generatedAt ${String(raw.generatedAt)}) -> ${jsonOut}, ${tsOut}`,
)
